package br.com.grupomm.mailing.enuns;

public enum AreaAnuarios {

	Adm(1,"Adm."),
	AdmFin(84,"Adm. / Fin."),
	Area(80,"Área"),
	Arquivo(2,"Arquivo"),
	Art(68,"Art."),
	Arte(3,"Arte"),
	Atend(4,"Atend."),
	Auditoria(5,"Auditoria"),
	DBA(6,"Banco de Dados"),
	Biblioteca(7,"Biblioteca"),
	Cena(97,"Cena"),
	Cinematografico(70,"Cinematográfico"),
	Circ(8,"Circ."),
	Classificados(99,"Classificados"),
	Coml(9,	"Coml."),
	Compras(10,"Compras"),
	Comunic(11,"Comunic."),
	Contas(83,"Contas"),
	Conteudo(95,"Conteúdo"),
	Controladoria(12,"Controladoria"),
	Corporativo(81,"Corporativo"),
	CPD(13,"CPD"),
	Criacao(14,"Criação"),
	Desenv(15,"Desenv."),
	Design(16,"Design"),
	Diagramacao(82,	"Diagramação"),
	Distrib(17,	"Distrib."),
	Edicao(74,"Edição"),
	Editl(18,"Editl."),
	Eng(62,"Eng."),
	Estudio(19,	"Estúdio"),
	Eventos(20,"Eventos"),
	Exec(56,"Exec."),
	Exp(21,"Exp."),
	Filmes(78,"Filmes"),
	Fin(22,"Fin."),
	Fotografia(43,"Fotografia"),
	Geral(55,"Geral"),
	Gov(23, "Gov."),
	Grafica(67,"Grafica"),
	Ilustracao(71,"Ilustração"),
	Imp(24,"Imp."),
	Imprensa(77,"Imprensa"),
	Indl(25,"Indl."),
	Informat(26,"Informát."),
	Internac(27,"Internac."),
	Internet(65,"Internet"),
	Jornal(28,"Jornal."),
	Jur(29,"Jur."),
	Logistica(30,"Logística"),
	Mercado(98,"Mercado"),
	Merchandising(32,"Merchandising"),
	Midia(33,"Mídia"),
	Mkt(31,"Mkt."),
	Musical(73,	"Musical"),
	Negs(72,"Negs."),
	Noticiario(66,"Noticiário"),
	NovosNegs(90,"Novos Negs."),
	Nuleo(85,"Núcleo"),
	NucleoDigital(87,"Núcleo Digital"),
	Opec(94,"Opec."),
	Oper(61,"Oper."),
	Patrimônio(34,"Patrimônio"),
	Pesq(35,"Pesq."),
	Pessoal(36,"Pessoal"),
	Planej(37,"Planej."),
	PlanejAtend(89,"Planej. e Atend."),
	Pres(60,"Pres."),
	Prod(38,"Prod."),
	ProdFilme(92,"Prod. Filme"),
	ProdGaf(39,"Prod. Gráf."),
	ProdSom(93,"Prod. Som"),
	Produto(40,"Produto"),
	Progr(41,"Progr."),
	ProgrAM(58,"Progr. AM"),
	ProgrFM(59,"Progr. FM"),
	Projs(75,"Projs."),
	Prom(42,"Prom."),
	Publ(64,"Publ."),
	Publicacoes(86,"Publicações"),
	Radio(69,"Rádio"),
	Redacao(44,	"Redação"),
	Regional(63,"Regional"),
	Relacionamento(96,"Relacionamento"),
	RelacoesPublicas(45,"Relações Públicas"),
	RH(46,"RH"),
	RTVC(47,"RTVC"),
	Sists(48,"Sists."),
	Suporte(76,"Suporte"),
	Suprimentos(49,"Suprimentos"),
	Tecnologia(50,"Tecn."),
	Tecn(57,"Técn."),
	Telemkt(51,"Telemkt."),
	TI(88,"TI"),
	Trafego(52,"Tráfego"),
	Trein(53,"Trein."),
	Vendas(54,"Vendas"),
	WebDesigner(79,"Web Designer");

	private final String nome;
	private final Integer id;

	private AreaAnuarios( Integer i, String s) {
		id=i;
		nome = s;
	}

	public String getNome(){
		return nome;
	}
	public Integer getId(){
		return id;
	}

}
